apiVersion: v1
kind: Service
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: ubuntu
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: ubuntu
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: openretriever/ubuntu1604-ping
        command: [ "/bin/bash", "-c", "sleep 30000" ]
        ports:
        - containerPort: 80
